const SPOTIFY_CLIENT_ID = "e87580a64e684080872551d411908a0a";
const LOCAL_SPOTIFY_REDIRECT_URI = "http://localhost:3000/callback";
const PRODUCTION_SPOTIFY_REDIRECT_URI = "https://spotify-philips-hue-album-sync.herokuapp.com/callback";
const PHILIPS_HUB_IP = "10.0.0.92";
const PHILIPS_HUB_USERNAME = "WZ1wvNs08Lp7Ru4bcVGPF45uPKbOJBoxqggD5wRq";

export {
  SPOTIFY_CLIENT_ID,
  PHILIPS_HUB_IP,
  PHILIPS_HUB_USERNAME,
  LOCAL_SPOTIFY_REDIRECT_URI,
  PRODUCTION_SPOTIFY_REDIRECT_URI,
};